### ISSUE TITLE
Add music!

### ISSUE THREAD

**Issue by thomas-pike** [thomas-pike/atoms-www#1]
The music from the Amiga game really fit well with the game and made it feel more interesting. Need to include this important feature!

**Comment by matiasbian** [comment]
Do you want that particular song or are you looking for a new one for the game?

**Comment by thomas-pike** [comment]
Ideally I'd like to have the original soundtrack, but I'm not sure about the legal ownership of that, so I'm open to the option of using something else too.

**Comment by thomas-pike** [comment]
Thanks to Daniel Reimann of www.amiga-news.de, I have been pointed to a copy of the original music file at http://aminet.net/package/mods/sets/MiscMods_m - I should be able to use this to make some web-compatible audio files for properly looped audio.
